namespace App
{
    using PlayerView;
    using System;
    using System.Collections.Generic;

    public static class ConfigAudio
    {
        public static List<AudioSourceType> AMBIENCE_AUDIO_SOURCES;
        public static List<AudioSourceType> GAMEPLAY_SFX_AUDIO_SOURCES;
        public static List<AudioSourceType> MUSIC_AUDIO_SOURCES;
        public static Dictionary<AudioGroupType, List<AudioSourceType>> SFX_AUDIO_GROUPS;
        public static List<AudioSourceType> UI_SFX_AUDIO_SOURCES;

        static ConfigAudio()
        {
            List<AudioSourceType> list = new List<AudioSourceType>();
            list.Add(AudioSourceType.Music_Boss);
            list.Add(AudioSourceType.Music_Gameplay);
            list.Add(AudioSourceType.Music_Frenzy);
            list.Add(AudioSourceType.Music_JingleFrenzyEnd);
            list.Add(AudioSourceType.Music_JingleVictory);
            list.Add(AudioSourceType.Music_JingleDefeat);
            list.Add(AudioSourceType.Music_JingleBoss);
            MUSIC_AUDIO_SOURCES = list;
            list = new List<AudioSourceType>();
            list.Add(AudioSourceType.Ambience_Dungeon);
            list.Add(AudioSourceType.Ambience_Cloudy);
            list.Add(AudioSourceType.Ambience_Winter);
            AMBIENCE_AUDIO_SOURCES = list;
            list = new List<AudioSourceType>();
            list.Add(AudioSourceType.SfxUi_BannerAnnounceFloor);
            list.Add(AudioSourceType.SfxUi_BannerAnnounceBoss);
            list.Add(AudioSourceType.SfxUi_RewardSlam);
            list.Add(AudioSourceType.SfxUi_RewardClaim);
            list.Add(AudioSourceType.SfxUi_ChestUnfold);
            list.Add(AudioSourceType.SfxUi_FlagAppear);
            list.Add(AudioSourceType.SfxUi_PlayerRankUp);
            list.Add(AudioSourceType.SfxUi_PlayerRankUpFrenzy);
            list.Add(AudioSourceType.SfxUi_SkillGain);
            list.Add(AudioSourceType.SfxUi_SkillEquip);
            list.Add(AudioSourceType.SfxUi_ItemGain);
            list.Add(AudioSourceType.SfxUi_ItemUnlock);
            list.Add(AudioSourceType.SfxUi_ItemRankUp01);
            list.Add(AudioSourceType.SfxUi_ItemRankUp02);
            list.Add(AudioSourceType.SfxUi_ItemSell);
            list.Add(AudioSourceType.SfxUi_RunestoneGain);
            list.Add(AudioSourceType.SfxUi_RunestoneSelect);
            list.Add(AudioSourceType.SfxUi_AchievementClaim);
            list.Add(AudioSourceType.SfxUi_ItemEquip_Weapon_Wood);
            list.Add(AudioSourceType.SfxUi_ItemEquip_Weapon_Metal);
            list.Add(AudioSourceType.SfxUi_ItemEquip_Armor_Leather);
            list.Add(AudioSourceType.SfxUi_ItemEquip_Armor_Metal);
            list.Add(AudioSourceType.SfxUi_ItemEquip_Helmet_Leather);
            list.Add(AudioSourceType.SfxUi_ItemEquip_Helmet_Metal);
            list.Add(AudioSourceType.SfxUi_BuyUpgrade);
            list.Add(AudioSourceType.SfxUi_Popup);
            list.Add(AudioSourceType.SfxUi_PopupTutorial);
            list.Add(AudioSourceType.SfxUi_NotificationGreat);
            list.Add(AudioSourceType.SfxUi_ButtonTab);
            list.Add(AudioSourceType.SfxUi_ButtonGeneric);
            list.Add(AudioSourceType.SfxUi_Revive);
            list.Add(AudioSourceType.SfxUi_ClockTick01);
            list.Add(AudioSourceType.SfxUi_ClockTick02);
            list.Add(AudioSourceType.SfxUi_ClockTick03);
            list.Add(AudioSourceType.SfxUi_ClockTick04);
            list.Add(AudioSourceType.SfxUi_Reroll01);
            list.Add(AudioSourceType.SfxUi_Reroll02);
            list.Add(AudioSourceType.SfxUi_Reroll03);
            list.Add(AudioSourceType.SfxUi_ResourceCoin01);
            list.Add(AudioSourceType.SfxUi_ResourceCoin02);
            list.Add(AudioSourceType.SfxUi_ResourceCoin03);
            list.Add(AudioSourceType.SfxUi_ResourceCoin04);
            list.Add(AudioSourceType.SfxUi_ResourceCoin05);
            list.Add(AudioSourceType.SfxUi_ResourceCoin06);
            list.Add(AudioSourceType.SfxUi_ResourceCoin07);
            list.Add(AudioSourceType.SfxUi_ResourceDiamond01);
            list.Add(AudioSourceType.SfxUi_ResourceDiamond02);
            list.Add(AudioSourceType.SfxUi_ResourceDiamond03);
            list.Add(AudioSourceType.SfxUi_ResourceDiamond04);
            list.Add(AudioSourceType.SfxUi_BagOpen01);
            list.Add(AudioSourceType.SfxUi_BagOpen02);
            list.Add(AudioSourceType.SfxUi_BagOpen03);
            list.Add(AudioSourceType.SfxUi_BagOpen04);
            list.Add(AudioSourceType.SfxUi_BagOpen05);
            list.Add(AudioSourceType.SfxUi_BagClose01);
            list.Add(AudioSourceType.SfxUi_BagClose02);
            list.Add(AudioSourceType.SfxUi_BagClose03);
            list.Add(AudioSourceType.SfxUi_BagClose04);
            list.Add(AudioSourceType.SfxUi_BagClose05);
            list.Add(AudioSourceType.SfxUi_BookOpen01);
            list.Add(AudioSourceType.SfxUi_BookOpen02);
            list.Add(AudioSourceType.SfxUi_BookOpen03);
            list.Add(AudioSourceType.SfxUi_BookClose01);
            list.Add(AudioSourceType.SfxUi_BookClose02);
            list.Add(AudioSourceType.SfxUi_BookClose03);
            list.Add(AudioSourceType.SfxUi_BookTurn01);
            list.Add(AudioSourceType.SfxUi_BookTurn02);
            list.Add(AudioSourceType.SfxUi_BookTurn03);
            list.Add(AudioSourceType.SfxUi_BookTurn04);
            list.Add(AudioSourceType.SfxUi_BookTurn05);
            list.Add(AudioSourceType.SfxUi_UISlam);
            UI_SFX_AUDIO_SOURCES = list;
            list = new List<AudioSourceType>();
            list.Add(AudioSourceType.SfxGameplay_HeroStepL01);
            list.Add(AudioSourceType.SfxGameplay_HeroStepL02);
            list.Add(AudioSourceType.SfxGameplay_HeroStepL03);
            list.Add(AudioSourceType.SfxGameplay_HeroStepL04);
            list.Add(AudioSourceType.SfxGameplay_HeroStepL05);
            list.Add(AudioSourceType.SfxGameplay_HeroStepL06);
            list.Add(AudioSourceType.SfxGameplay_HeroStepR01);
            list.Add(AudioSourceType.SfxGameplay_HeroStepR02);
            list.Add(AudioSourceType.SfxGameplay_HeroStepR03);
            list.Add(AudioSourceType.SfxGameplay_HeroStepR04);
            list.Add(AudioSourceType.SfxGameplay_HeroStepR05);
            list.Add(AudioSourceType.SfxGameplay_HeroStepR06);
            list.Add(AudioSourceType.SfxGameplay_HeroStepGrassL01);
            list.Add(AudioSourceType.SfxGameplay_HeroStepGrassL02);
            list.Add(AudioSourceType.SfxGameplay_HeroStepGrassL03);
            list.Add(AudioSourceType.SfxGameplay_HeroStepGrassL04);
            list.Add(AudioSourceType.SfxGameplay_HeroStepGrassL05);
            list.Add(AudioSourceType.SfxGameplay_HeroStepGrassL06);
            list.Add(AudioSourceType.SfxGameplay_HeroStepGrassR01);
            list.Add(AudioSourceType.SfxGameplay_HeroStepGrassR02);
            list.Add(AudioSourceType.SfxGameplay_HeroStepGrassR03);
            list.Add(AudioSourceType.SfxGameplay_HeroStepGrassR04);
            list.Add(AudioSourceType.SfxGameplay_HeroStepGrassR05);
            list.Add(AudioSourceType.SfxGameplay_HeroStepGrassR06);
            list.Add(AudioSourceType.SfxGameplay_HeroStepIceL01);
            list.Add(AudioSourceType.SfxGameplay_HeroStepIceL02);
            list.Add(AudioSourceType.SfxGameplay_HeroStepIceL03);
            list.Add(AudioSourceType.SfxGameplay_HeroStepIceL04);
            list.Add(AudioSourceType.SfxGameplay_HeroStepIceL05);
            list.Add(AudioSourceType.SfxGameplay_HeroStepIceL06);
            list.Add(AudioSourceType.SfxGameplay_HeroStepIceR01);
            list.Add(AudioSourceType.SfxGameplay_HeroStepIceR02);
            list.Add(AudioSourceType.SfxGameplay_HeroStepIceR03);
            list.Add(AudioSourceType.SfxGameplay_HeroStepIceR04);
            list.Add(AudioSourceType.SfxGameplay_HeroStepIceR05);
            list.Add(AudioSourceType.SfxGameplay_HeroStepIceR06);
            list.Add(AudioSourceType.SfxGameplay_HeroArmorLayer);
            list.Add(AudioSourceType.SfxGameplay_HeroSwing01);
            list.Add(AudioSourceType.SfxGameplay_HeroSwing02);
            list.Add(AudioSourceType.SfxGameplay_HeroSwing03);
            list.Add(AudioSourceType.SfxGameplay_HeroSwing04);
            list.Add(AudioSourceType.SfxGameplay_HeroSwing05);
            list.Add(AudioSourceType.SfxGameplay_HeroHitWood01);
            list.Add(AudioSourceType.SfxGameplay_HeroHitWood02);
            list.Add(AudioSourceType.SfxGameplay_HeroHitWood03);
            list.Add(AudioSourceType.SfxGameplay_HeroHitIce01);
            list.Add(AudioSourceType.SfxGameplay_HeroHitIce02);
            list.Add(AudioSourceType.SfxGameplay_HeroHitIce03);
            list.Add(AudioSourceType.SfxGameplay_HeroHitSword01);
            list.Add(AudioSourceType.SfxGameplay_HeroHitSword02);
            list.Add(AudioSourceType.SfxGameplay_HeroHitSword03);
            list.Add(AudioSourceType.SfxGameplay_HeroHitSword04);
            list.Add(AudioSourceType.SfxGameplay_HeroHitSword05);
            list.Add(AudioSourceType.SfxGameplay_HeroHitSword06);
            list.Add(AudioSourceType.SfxGameplay_HeroHitSword07);
            list.Add(AudioSourceType.SfxGameplay_HeroHitSword08);
            list.Add(AudioSourceType.SfxGameplay_HeroHitSword09);
            list.Add(AudioSourceType.SfxGameplay_HeroHitSword10);
            list.Add(AudioSourceType.SfxGameplay_HeroHitSword11);
            list.Add(AudioSourceType.SfxGameplay_HeroHitSword12);
            list.Add(AudioSourceType.SfxGameplay_HeroHitSword13);
            list.Add(AudioSourceType.SfxGameplay_HeroHitCrit);
            list.Add(AudioSourceType.SfxGameplay_HeroPain01);
            list.Add(AudioSourceType.SfxGameplay_HeroPain02);
            list.Add(AudioSourceType.SfxGameplay_HeroDeath);
            list.Add(AudioSourceType.SfxGameplay_HeroAscend);
            list.Add(AudioSourceType.SfxGameplay_NextFloorVanish);
            list.Add(AudioSourceType.SfxGameplay_NextFloorClouds);
            list.Add(AudioSourceType.SfxGameplay_NextFloorCloudsShort);
            list.Add(AudioSourceType.SfxGameplay_NextFloorArrive);
            list.Add(AudioSourceType.SfxGameplay_SkillLeapTrigger);
            list.Add(AudioSourceType.SfxGameplay_SkillLeapSlam);
            list.Add(AudioSourceType.SfxGameplay_SkillClone);
            list.Add(AudioSourceType.SfxGameplay_SkillCloneDeath);
            list.Add(AudioSourceType.SfxGameplay_SkillWhirlwind01);
            list.Add(AudioSourceType.SfxGameplay_SkillWhirlwind02);
            list.Add(AudioSourceType.SfxGameplay_SkillWhirlwind03);
            list.Add(AudioSourceType.SfxGameplay_SkillWhirlwind6x01);
            list.Add(AudioSourceType.SfxGameplay_SkillWhirlwind6x02);
            list.Add(AudioSourceType.SfxGameplay_SkillWhirlwind6x03);
            list.Add(AudioSourceType.SfxGameplay_SkillWhirlwindFreeze01);
            list.Add(AudioSourceType.SfxGameplay_SkillWhirlwindFreeze02);
            list.Add(AudioSourceType.SfxGameplay_SkillWhirlwindFreeze03);
            list.Add(AudioSourceType.SfxGameplay_SkillWhirlwindKnockback);
            list.Add(AudioSourceType.SfxGameplay_SkillSlam);
            list.Add(AudioSourceType.SfxGameplay_SkillSlamRocky01);
            list.Add(AudioSourceType.SfxGameplay_SkillSlamRocky02);
            list.Add(AudioSourceType.SfxGameplay_SkillSlamRocky03);
            list.Add(AudioSourceType.SfxGameplay_SkillSlamAftershock01);
            list.Add(AudioSourceType.SfxGameplay_SkillSlamAftershock02);
            list.Add(AudioSourceType.SfxGameplay_SkillSlamAftershock03);
            list.Add(AudioSourceType.SfxGameplay_SkillSlamAftershock04);
            list.Add(AudioSourceType.SfxGameplay_SkillSlamAftershock05);
            list.Add(AudioSourceType.SfxGameplay_SkillOmnislash);
            list.Add(AudioSourceType.SfxGameplay_SkillOmnislashDash01);
            list.Add(AudioSourceType.SfxGameplay_SkillOmnislashDash02);
            list.Add(AudioSourceType.SfxGameplay_SkillOmnislashDash03);
            list.Add(AudioSourceType.SfxGameplay_SkillOmnislashHit01);
            list.Add(AudioSourceType.SfxGameplay_SkillOmnislashHit02);
            list.Add(AudioSourceType.SfxGameplay_SkillOmnislashHit03);
            list.Add(AudioSourceType.SfxGameplay_SkillOmnislashHit04);
            list.Add(AudioSourceType.SfxGameplay_SkillImplosion);
            list.Add(AudioSourceType.SfxGameplay_SkillImplosionCast);
            list.Add(AudioSourceType.SfxGameplay_SkillSummonMinions);
            list.Add(AudioSourceType.SfxGameplay_SkillSplit);
            list.Add(AudioSourceType.SfxGameplay_SkillShield);
            list.Add(AudioSourceType.SfxGameplay_SkillHeal);
            list.Add(AudioSourceType.SfxGameplay_ResourceCoin01);
            list.Add(AudioSourceType.SfxGameplay_ResourceCoin02);
            list.Add(AudioSourceType.SfxGameplay_ResourceCoin03);
            list.Add(AudioSourceType.SfxGameplay_ResourceCoin04);
            list.Add(AudioSourceType.SfxGameplay_ResourceCoin05);
            list.Add(AudioSourceType.SfxGameplay_ResourceCoin06);
            list.Add(AudioSourceType.SfxGameplay_ResourceCoin07);
            list.Add(AudioSourceType.SfxGameplay_ResourceDiamond01);
            list.Add(AudioSourceType.SfxGameplay_ResourceDiamond02);
            list.Add(AudioSourceType.SfxGameplay_ResourceDiamond03);
            list.Add(AudioSourceType.SfxGameplay_ResourceDiamond04);
            list.Add(AudioSourceType.SfxGameplay_CritterAttack01);
            list.Add(AudioSourceType.SfxGameplay_CritterAttack02);
            list.Add(AudioSourceType.SfxGameplay_CritterAttack03);
            list.Add(AudioSourceType.SfxGameplay_CritterVoice01);
            list.Add(AudioSourceType.SfxGameplay_CritterVoice02);
            list.Add(AudioSourceType.SfxGameplay_CritterVoice03);
            list.Add(AudioSourceType.SfxGameplay_CritterDeath01);
            list.Add(AudioSourceType.SfxGameplay_CritterDeath02);
            list.Add(AudioSourceType.SfxGameplay_CritterDeath03);
            list.Add(AudioSourceType.SfxGameplay_DragonAttack01);
            list.Add(AudioSourceType.SfxGameplay_DragonAttack02);
            list.Add(AudioSourceType.SfxGameplay_DragonAttack03);
            list.Add(AudioSourceType.SfxGameplay_DragonAttack04);
            list.Add(AudioSourceType.SfxGameplay_EnemyAttackFireball01);
            list.Add(AudioSourceType.SfxGameplay_EnemyAttackFireball02);
            list.Add(AudioSourceType.SfxGameplay_EnemyAttackFireball03);
            list.Add(AudioSourceType.SfxGameplay_SkeletonRattle01);
            list.Add(AudioSourceType.SfxGameplay_SkeletonRattle02);
            list.Add(AudioSourceType.SfxGameplay_SkeletonRattle03);
            list.Add(AudioSourceType.SfxGameplay_SkeletonRattle04);
            list.Add(AudioSourceType.SfxGameplay_SkeletonRattle05);
            list.Add(AudioSourceType.SfxGameplay_SkeletonDeath01);
            list.Add(AudioSourceType.SfxGameplay_SkeletonDeath02);
            list.Add(AudioSourceType.SfxGameplay_SkeletonDeath03);
            list.Add(AudioSourceType.SfxGameplay_PygmyNoise01);
            list.Add(AudioSourceType.SfxGameplay_PygmyNoise02);
            list.Add(AudioSourceType.SfxGameplay_PygmyNoise03);
            list.Add(AudioSourceType.SfxGameplay_PygmyDeath01);
            list.Add(AudioSourceType.SfxGameplay_PygmyDeath02);
            list.Add(AudioSourceType.SfxGameplay_PygmyDeath03);
            list.Add(AudioSourceType.SfxGameplay_PygmyRattle01);
            list.Add(AudioSourceType.SfxGameplay_PygmyRattle02);
            list.Add(AudioSourceType.SfxGameplay_PygmyRattle03);
            list.Add(AudioSourceType.SfxGameplay_PygmyRattle04);
            list.Add(AudioSourceType.SfxGameplay_CrocNoise01);
            list.Add(AudioSourceType.SfxGameplay_CrocNoise02);
            list.Add(AudioSourceType.SfxGameplay_CrocNoise03);
            list.Add(AudioSourceType.SfxGameplay_CrocDeath01);
            list.Add(AudioSourceType.SfxGameplay_CrocDeath02);
            list.Add(AudioSourceType.SfxGameplay_AnubisNoise01);
            list.Add(AudioSourceType.SfxGameplay_AnubisNoise02);
            list.Add(AudioSourceType.SfxGameplay_AnubisNoise03);
            list.Add(AudioSourceType.SfxGameplay_AnubisNoise04);
            list.Add(AudioSourceType.SfxGameplay_AnubisDeath01);
            list.Add(AudioSourceType.SfxGameplay_AnubisDeath02);
            list.Add(AudioSourceType.SfxGameplay_AnubisDeath03);
            list.Add(AudioSourceType.SfxGameplay_GoblinNoise01);
            list.Add(AudioSourceType.SfxGameplay_GoblinNoise02);
            list.Add(AudioSourceType.SfxGameplay_GoblinNoise03);
            list.Add(AudioSourceType.SfxGameplay_GoblinNoise04);
            list.Add(AudioSourceType.SfxGameplay_GoblinDeath01);
            list.Add(AudioSourceType.SfxGameplay_GoblinDeath02);
            list.Add(AudioSourceType.SfxGameplay_GoblinDeath03);
            list.Add(AudioSourceType.SfxGameplay_MummyNoise01);
            list.Add(AudioSourceType.SfxGameplay_MummyNoise02);
            list.Add(AudioSourceType.SfxGameplay_MummyNoise03);
            list.Add(AudioSourceType.SfxGameplay_MummyDeath01);
            list.Add(AudioSourceType.SfxGameplay_MummyDeath02);
            list.Add(AudioSourceType.SfxGameplay_MummyDeath03);
            list.Add(AudioSourceType.SfxGameplay_RatNoise01);
            list.Add(AudioSourceType.SfxGameplay_RatNoise02);
            list.Add(AudioSourceType.SfxGameplay_RatNoise03);
            list.Add(AudioSourceType.SfxGameplay_RatNoise04);
            list.Add(AudioSourceType.SfxGameplay_RatDeath01);
            list.Add(AudioSourceType.SfxGameplay_RatDeath02);
            list.Add(AudioSourceType.SfxGameplay_RatDeath03);
            list.Add(AudioSourceType.SfxGameplay_RatDeath04);
            list.Add(AudioSourceType.SfxGameplay_YetiNoise01);
            list.Add(AudioSourceType.SfxGameplay_YetiNoise02);
            list.Add(AudioSourceType.SfxGameplay_YetiNoise03);
            list.Add(AudioSourceType.SfxGameplay_YetiNoise04);
            list.Add(AudioSourceType.SfxGameplay_YetiDeath01);
            list.Add(AudioSourceType.SfxGameplay_YetiDeath02);
            list.Add(AudioSourceType.SfxGameplay_YetiDeath03);
            list.Add(AudioSourceType.SfxGameplay_YetiDeath04);
            list.Add(AudioSourceType.SfxGameplay_ShroomNoise01);
            list.Add(AudioSourceType.SfxGameplay_ShroomNoise02);
            list.Add(AudioSourceType.SfxGameplay_ShroomNoise03);
            list.Add(AudioSourceType.SfxGameplay_ShroomDeath01);
            list.Add(AudioSourceType.SfxGameplay_ShroomDeath02);
            list.Add(AudioSourceType.SfxGameplay_ShroomDeath03);
            list.Add(AudioSourceType.SfxGameplay_ShroomPuff01);
            list.Add(AudioSourceType.SfxGameplay_ShroomPuff02);
            list.Add(AudioSourceType.SfxGameplay_ShroomPuff03);
            list.Add(AudioSourceType.SfxGameplay_ShroomPuff04);
            list.Add(AudioSourceType.SfxGameplay_WoodenShieldLayer01);
            list.Add(AudioSourceType.SfxGameplay_WoodenShieldLayer02);
            list.Add(AudioSourceType.SfxGameplay_WoodenShieldLayer03);
            list.Add(AudioSourceType.SfxGameplay_WoodenShieldLayer04);
            list.Add(AudioSourceType.SfxGameplay_JellyDeath01);
            list.Add(AudioSourceType.SfxGameplay_JellyDeath02);
            list.Add(AudioSourceType.SfxGameplay_JellyMove01);
            list.Add(AudioSourceType.SfxGameplay_JellyMove02);
            list.Add(AudioSourceType.SfxGameplay_JellyMove03);
            list.Add(AudioSourceType.SfxGameplay_JellyMove04);
            list.Add(AudioSourceType.SfxGameplay_JellyMove05);
            list.Add(AudioSourceType.SfxGameplay_JellyMove06);
            list.Add(AudioSourceType.SfxGameplay_WorgDeath);
            list.Add(AudioSourceType.SfxGameplay_WorgNoise1);
            list.Add(AudioSourceType.SfxGameplay_WorgNoise2);
            list.Add(AudioSourceType.SfxGameplay_FrenzyTeleport01);
            list.Add(AudioSourceType.SfxGameplay_FrenzyTeleport02);
            list.Add(AudioSourceType.SfxGameplay_FrenzyTeleport03);
            list.Add(AudioSourceType.SfxGameplay_ResourceDrop);
            list.Add(AudioSourceType.SfxGameplay_BossSkillBuildup);
            list.Add(AudioSourceType.SfxGameplay_PetWalrusVoice01);
            list.Add(AudioSourceType.SfxGameplay_PetWalrusVoice02);
            list.Add(AudioSourceType.SfxGameplay_PetWalrusVoice03);
            list.Add(AudioSourceType.SfxGameplay_PetWalrusVoice04);
            list.Add(AudioSourceType.SfxGameplay_PetWalrusVoice05);
            list.Add(AudioSourceType.SfxGameplay_PetMooseVoice01);
            list.Add(AudioSourceType.SfxGameplay_PetMooseVoice02);
            list.Add(AudioSourceType.SfxGameplay_PetMooseVoice03);
            list.Add(AudioSourceType.SfxGameplay_PetMooseVoice04);
            list.Add(AudioSourceType.SfxGameplay_PetMooseVoice05);
            list.Add(AudioSourceType.SfxGameplay_PetDogBark01);
            list.Add(AudioSourceType.SfxGameplay_PetDogBark02);
            list.Add(AudioSourceType.SfxGameplay_PetDogBark03);
            list.Add(AudioSourceType.SfxGameplay_PetDogBark04);
            list.Add(AudioSourceType.SfxGameplay_PetDogBark05);
            list.Add(AudioSourceType.SfxGameplay_PetSharkBite01);
            list.Add(AudioSourceType.SfxGameplay_PetSharkBite02);
            list.Add(AudioSourceType.SfxGameplay_PetSharkBite03);
            list.Add(AudioSourceType.SfxGameplay_PetGorillaVoice01);
            list.Add(AudioSourceType.SfxGameplay_PetGorillaVoice02);
            list.Add(AudioSourceType.SfxGameplay_PetGorillaVoice03);
            list.Add(AudioSourceType.SfxGameplay_PetGorillaVoice04);
            list.Add(AudioSourceType.SfxGameplay_PetGorillaVoice05);
            list.Add(AudioSourceType.SfxGameplay_PetCrabVoice01);
            list.Add(AudioSourceType.SfxGameplay_PetCrabVoice02);
            list.Add(AudioSourceType.SfxGameplay_PetCrabVoice03);
            list.Add(AudioSourceType.SfxGameplay_PetCrabVoice04);
            list.Add(AudioSourceType.SfxGameplay_PetCrabVoice05);
            list.Add(AudioSourceType.SfxGameplay_PetTreeRustle01);
            list.Add(AudioSourceType.SfxGameplay_PetTreeRustle02);
            list.Add(AudioSourceType.SfxGameplay_PetTreeRustle03);
            list.Add(AudioSourceType.SfxGameplay_PetRamVoice01);
            list.Add(AudioSourceType.SfxGameplay_PetRamVoice02);
            list.Add(AudioSourceType.SfxGameplay_PetRamVoice03);
            list.Add(AudioSourceType.SfxGameplay_PetJadeVoice01);
            list.Add(AudioSourceType.SfxGameplay_PetJadeVoice02);
            list.Add(AudioSourceType.SfxGameplay_PetJadeVoice03);
            list.Add(AudioSourceType.SfxGameplay_PetJadeVoice04);
            list.Add(AudioSourceType.SfxGameplay_PetJadeVoice05);
            list.Add(AudioSourceType.SfxGameplay_PetChesterVoice01);
            list.Add(AudioSourceType.SfxGameplay_PetChesterVoice02);
            list.Add(AudioSourceType.SfxGameplay_PetChesterVoice03);
            list.Add(AudioSourceType.SfxGameplay_PetChesterVoice04);
            list.Add(AudioSourceType.SfxGameplay_PetAttackCoin01);
            list.Add(AudioSourceType.SfxGameplay_PetAttackCoin02);
            list.Add(AudioSourceType.SfxGameplay_PetAttackCoin03);
            list.Add(AudioSourceType.SfxGameplay_PetAttackCoin04);
            list.Add(AudioSourceType.SfxGameplay_PetAttackPunch01);
            list.Add(AudioSourceType.SfxGameplay_PetAttackPunch02);
            list.Add(AudioSourceType.SfxGameplay_PetAttackPunch03);
            list.Add(AudioSourceType.SfxGameplay_PetAttackPunch04);
            list.Add(AudioSourceType.SfxGameplay_PetAttackGunshot01);
            list.Add(AudioSourceType.SfxGameplay_PetAttackGunshot02);
            list.Add(AudioSourceType.SfxGameplay_PetAttackGunshot03);
            list.Add(AudioSourceType.SfxGameplay_PetAttackGunshot04);
            list.Add(AudioSourceType.SfxGameplay_PetAttackThrow01);
            list.Add(AudioSourceType.SfxGameplay_PetAttackThrow02);
            list.Add(AudioSourceType.SfxGameplay_PetAttackThrow03);
            list.Add(AudioSourceType.SfxGameplay_PetAttackSquirt01);
            list.Add(AudioSourceType.SfxGameplay_PetAttackSquirt02);
            list.Add(AudioSourceType.SfxGameplay_PetAttackSquirt03);
            list.Add(AudioSourceType.SfxGameplay_PetAttackSquirt04);
            list.Add(AudioSourceType.SfxGameplay_PetAttackHeadbutt01);
            list.Add(AudioSourceType.SfxGameplay_PetAttackHeadbutt02);
            list.Add(AudioSourceType.SfxGameplay_PetAttackHeadbutt03);
            list.Add(AudioSourceType.SfxGameplay_PetAttackHitFoliage01);
            list.Add(AudioSourceType.SfxGameplay_PetAttackHitFoliage02);
            list.Add(AudioSourceType.SfxGameplay_PetAttackHitFoliage03);
            list.Add(AudioSourceType.SfxGameplay_PetAttackHitFoliage04);
            list.Add(AudioSourceType.SfxGameplay_PetAttackHitBoulder01);
            list.Add(AudioSourceType.SfxGameplay_PetAttackHitBoulder02);
            list.Add(AudioSourceType.SfxGameplay_PetAttackHitBoulder03);
            list.Add(AudioSourceType.SfxGameplay_PetAttackHitBoulder04);
            list.Add(AudioSourceType.SfxGameplay_PetAttackHitBoulder05);
            list.Add(AudioSourceType.SfxGameplay_PetSkillDash01);
            list.Add(AudioSourceType.SfxGameplay_PetSkillDash02);
            list.Add(AudioSourceType.SfxGameplay_PetSkillDash03);
            list.Add(AudioSourceType.SfxGameplay_PetSkillLeapTrigger);
            list.Add(AudioSourceType.SfxGameplay_PetSkillLeapSlam);
            list.Add(AudioSourceType.SfxGameplay_PetSkillWhirl01);
            list.Add(AudioSourceType.SfxGameplay_PetSkillWhirl02);
            list.Add(AudioSourceType.SfxGameplay_PetSkillWhirl03);
            list.Add(AudioSourceType.SfxGameplay_SmashPot01);
            list.Add(AudioSourceType.SfxGameplay_SmashPot02);
            list.Add(AudioSourceType.SfxGameplay_SmashPot03);
            list.Add(AudioSourceType.SfxGameplay_SmashPot04);
            list.Add(AudioSourceType.SfxGameplay_SmashCrate01);
            list.Add(AudioSourceType.SfxGameplay_SmashCrate02);
            list.Add(AudioSourceType.SfxGameplay_SmashCrate03);
            list.Add(AudioSourceType.SfxGameplay_SmashCrate04);
            list.Add(AudioSourceType.SfxGameplay_SmashPumpkin01);
            list.Add(AudioSourceType.SfxGameplay_SmashPumpkin02);
            list.Add(AudioSourceType.SfxGameplay_SmashPumpkin03);
            list.Add(AudioSourceType.SfxGameplay_SmashPumpkin04);
            list.Add(AudioSourceType.SfxGameplay_SmashPoison01);
            list.Add(AudioSourceType.SfxGameplay_SmashPoison02);
            list.Add(AudioSourceType.SfxGameplay_SmashPoison03);
            list.Add(AudioSourceType.SfxGameplay_SmashPoison04);
            GAMEPLAY_SFX_AUDIO_SOURCES = list;
            Dictionary<AudioGroupType, List<AudioSourceType>> dictionary = new Dictionary<AudioGroupType, List<AudioSourceType>>(new AudioGroupTypeBoxAvoidanceComparer());
            list = new List<AudioSourceType>();
            list.Add(AudioSourceType.SfxGameplay_HeroStepL01);
            list.Add(AudioSourceType.SfxGameplay_HeroStepL02);
            list.Add(AudioSourceType.SfxGameplay_HeroStepL03);
            list.Add(AudioSourceType.SfxGameplay_HeroStepL04);
            list.Add(AudioSourceType.SfxGameplay_HeroStepL05);
            list.Add(AudioSourceType.SfxGameplay_HeroStepL06);
            dictionary.Add(AudioGroupType.SfxGrpGameplay_HeroStepL, list);
            list = new List<AudioSourceType>();
            list.Add(AudioSourceType.SfxGameplay_HeroStepR01);
            list.Add(AudioSourceType.SfxGameplay_HeroStepR02);
            list.Add(AudioSourceType.SfxGameplay_HeroStepR03);
            list.Add(AudioSourceType.SfxGameplay_HeroStepR04);
            list.Add(AudioSourceType.SfxGameplay_HeroStepR05);
            list.Add(AudioSourceType.SfxGameplay_HeroStepR06);
            dictionary.Add(AudioGroupType.SfxGrpGameplay_HeroStepR, list);
            list = new List<AudioSourceType>();
            list.Add(AudioSourceType.SfxGameplay_HeroStepGrassL01);
            list.Add(AudioSourceType.SfxGameplay_HeroStepGrassL02);
            list.Add(AudioSourceType.SfxGameplay_HeroStepGrassL03);
            list.Add(AudioSourceType.SfxGameplay_HeroStepGrassL04);
            list.Add(AudioSourceType.SfxGameplay_HeroStepGrassL05);
            list.Add(AudioSourceType.SfxGameplay_HeroStepGrassL06);
            dictionary.Add(AudioGroupType.SfxGrpGameplay_HeroStepGrassL, list);
            list = new List<AudioSourceType>();
            list.Add(AudioSourceType.SfxGameplay_HeroStepGrassR01);
            list.Add(AudioSourceType.SfxGameplay_HeroStepGrassR02);
            list.Add(AudioSourceType.SfxGameplay_HeroStepGrassR03);
            list.Add(AudioSourceType.SfxGameplay_HeroStepGrassR04);
            list.Add(AudioSourceType.SfxGameplay_HeroStepGrassR05);
            list.Add(AudioSourceType.SfxGameplay_HeroStepGrassR06);
            dictionary.Add(AudioGroupType.SfxGrpGameplay_HeroStepGrassR, list);
            list = new List<AudioSourceType>();
            list.Add(AudioSourceType.SfxGameplay_HeroStepIceL01);
            list.Add(AudioSourceType.SfxGameplay_HeroStepIceL02);
            list.Add(AudioSourceType.SfxGameplay_HeroStepIceL03);
            list.Add(AudioSourceType.SfxGameplay_HeroStepIceL04);
            list.Add(AudioSourceType.SfxGameplay_HeroStepIceL05);
            list.Add(AudioSourceType.SfxGameplay_HeroStepIceL06);
            dictionary.Add(AudioGroupType.SfxGrpGameplay_HeroStepIceL, list);
            list = new List<AudioSourceType>();
            list.Add(AudioSourceType.SfxGameplay_HeroStepIceR01);
            list.Add(AudioSourceType.SfxGameplay_HeroStepIceR02);
            list.Add(AudioSourceType.SfxGameplay_HeroStepIceR03);
            list.Add(AudioSourceType.SfxGameplay_HeroStepIceR04);
            list.Add(AudioSourceType.SfxGameplay_HeroStepIceR05);
            list.Add(AudioSourceType.SfxGameplay_HeroStepIceR06);
            dictionary.Add(AudioGroupType.SfxGrpGameplay_HeroStepIceR, list);
            list = new List<AudioSourceType>();
            list.Add(AudioSourceType.SfxGameplay_HeroSwing01);
            list.Add(AudioSourceType.SfxGameplay_HeroSwing02);
            list.Add(AudioSourceType.SfxGameplay_HeroSwing03);
            list.Add(AudioSourceType.SfxGameplay_HeroSwing04);
            list.Add(AudioSourceType.SfxGameplay_HeroSwing05);
            dictionary.Add(AudioGroupType.SfxGrpGameplay_HeroSwing, list);
            list = new List<AudioSourceType>();
            list.Add(AudioSourceType.SfxGameplay_HeroHitWood01);
            list.Add(AudioSourceType.SfxGameplay_HeroHitWood02);
            list.Add(AudioSourceType.SfxGameplay_HeroHitWood03);
            dictionary.Add(AudioGroupType.SfxGrpGameplay_HeroHitWood, list);
            list = new List<AudioSourceType>();
            list.Add(AudioSourceType.SfxGameplay_HeroHitIce01);
            list.Add(AudioSourceType.SfxGameplay_HeroHitIce02);
            list.Add(AudioSourceType.SfxGameplay_HeroHitIce03);
            dictionary.Add(AudioGroupType.SfxGrpGameplay_HeroHitIce, list);
            list = new List<AudioSourceType>();
            list.Add(AudioSourceType.SfxGameplay_HeroHitSword01);
            list.Add(AudioSourceType.SfxGameplay_HeroHitSword02);
            list.Add(AudioSourceType.SfxGameplay_HeroHitSword03);
            list.Add(AudioSourceType.SfxGameplay_HeroHitSword04);
            list.Add(AudioSourceType.SfxGameplay_HeroHitSword05);
            list.Add(AudioSourceType.SfxGameplay_HeroHitSword06);
            list.Add(AudioSourceType.SfxGameplay_HeroHitSword07);
            list.Add(AudioSourceType.SfxGameplay_HeroHitSword08);
            list.Add(AudioSourceType.SfxGameplay_HeroHitSword09);
            list.Add(AudioSourceType.SfxGameplay_HeroHitSword10);
            list.Add(AudioSourceType.SfxGameplay_HeroHitSword11);
            list.Add(AudioSourceType.SfxGameplay_HeroHitSword12);
            list.Add(AudioSourceType.SfxGameplay_HeroHitSword13);
            dictionary.Add(AudioGroupType.SfxGrpGameplay_HeroHitSword, list);
            list = new List<AudioSourceType>();
            list.Add(AudioSourceType.SfxGameplay_HeroPain01);
            list.Add(AudioSourceType.SfxGameplay_HeroPain02);
            dictionary.Add(AudioGroupType.SfxGrpGameplay_HeroPain, list);
            list = new List<AudioSourceType>();
            list.Add(AudioSourceType.SfxGameplay_SkillWhirlwind01);
            list.Add(AudioSourceType.SfxGameplay_SkillWhirlwind02);
            list.Add(AudioSourceType.SfxGameplay_SkillWhirlwind03);
            dictionary.Add(AudioGroupType.SfxGrpGameplay_SkillWhirlwind, list);
            list = new List<AudioSourceType>();
            list.Add(AudioSourceType.SfxGameplay_SkillWhirlwindFreeze01);
            list.Add(AudioSourceType.SfxGameplay_SkillWhirlwindFreeze02);
            list.Add(AudioSourceType.SfxGameplay_SkillWhirlwindFreeze03);
            dictionary.Add(AudioGroupType.SfxGrpGameplay_SkillWhirlwindFreeze, list);
            list = new List<AudioSourceType>();
            list.Add(AudioSourceType.SfxGameplay_SkillWhirlwind6x01);
            list.Add(AudioSourceType.SfxGameplay_SkillWhirlwind6x02);
            list.Add(AudioSourceType.SfxGameplay_SkillWhirlwind6x03);
            dictionary.Add(AudioGroupType.SfxGrpGameplay_SkillWhirlwind6x, list);
            list = new List<AudioSourceType>();
            list.Add(AudioSourceType.SfxGameplay_SkillOmnislashHit01);
            list.Add(AudioSourceType.SfxGameplay_SkillOmnislashHit02);
            list.Add(AudioSourceType.SfxGameplay_SkillOmnislashHit03);
            list.Add(AudioSourceType.SfxGameplay_SkillOmnislashHit04);
            dictionary.Add(AudioGroupType.SfxGrpGameplay_SkillOmnislashHit, list);
            list = new List<AudioSourceType>();
            list.Add(AudioSourceType.SfxGameplay_SkillOmnislashDash01);
            list.Add(AudioSourceType.SfxGameplay_SkillOmnislashDash02);
            list.Add(AudioSourceType.SfxGameplay_SkillOmnislashDash03);
            dictionary.Add(AudioGroupType.SfxGrpGameplay_SkillOmnislashDash, list);
            list = new List<AudioSourceType>();
            list.Add(AudioSourceType.SfxGameplay_SkillSlamRocky01);
            list.Add(AudioSourceType.SfxGameplay_SkillSlamRocky02);
            list.Add(AudioSourceType.SfxGameplay_SkillSlamRocky03);
            dictionary.Add(AudioGroupType.SfxGrpGameplay_SkillSlamRocky, list);
            list = new List<AudioSourceType>();
            list.Add(AudioSourceType.SfxGameplay_SkillSlamAftershock01);
            list.Add(AudioSourceType.SfxGameplay_SkillSlamAftershock02);
            list.Add(AudioSourceType.SfxGameplay_SkillSlamAftershock03);
            list.Add(AudioSourceType.SfxGameplay_SkillSlamAftershock04);
            list.Add(AudioSourceType.SfxGameplay_SkillSlamAftershock05);
            dictionary.Add(AudioGroupType.SfxGrpGameplay_SkillSlamAftershock, list);
            list = new List<AudioSourceType>();
            list.Add(AudioSourceType.SfxGameplay_EnemyAttackFireball01);
            list.Add(AudioSourceType.SfxGameplay_EnemyAttackFireball02);
            list.Add(AudioSourceType.SfxGameplay_EnemyAttackFireball03);
            dictionary.Add(AudioGroupType.SfxGrpGameplay_EnemyAttackFireball, list);
            list = new List<AudioSourceType>();
            list.Add(AudioSourceType.SfxGameplay_CritterAttack01);
            list.Add(AudioSourceType.SfxGameplay_CritterAttack02);
            list.Add(AudioSourceType.SfxGameplay_CritterAttack03);
            dictionary.Add(AudioGroupType.SfxGrpGameplay_CritterAttack, list);
            list = new List<AudioSourceType>();
            list.Add(AudioSourceType.SfxGameplay_CritterVoice01);
            list.Add(AudioSourceType.SfxGameplay_CritterVoice02);
            list.Add(AudioSourceType.SfxGameplay_CritterVoice03);
            dictionary.Add(AudioGroupType.SfxGrpGameplay_CritterVoice, list);
            list = new List<AudioSourceType>();
            list.Add(AudioSourceType.SfxGameplay_CritterDeath01);
            list.Add(AudioSourceType.SfxGameplay_CritterDeath02);
            list.Add(AudioSourceType.SfxGameplay_CritterDeath03);
            dictionary.Add(AudioGroupType.SfxGrpGameplay_CritterDeath, list);
            list = new List<AudioSourceType>();
            list.Add(AudioSourceType.SfxGameplay_DragonAttack01);
            list.Add(AudioSourceType.SfxGameplay_DragonAttack02);
            list.Add(AudioSourceType.SfxGameplay_DragonAttack03);
            list.Add(AudioSourceType.SfxGameplay_DragonAttack04);
            dictionary.Add(AudioGroupType.SfxGrpGameplay_DragonAttack, list);
            list = new List<AudioSourceType>();
            list.Add(AudioSourceType.SfxGameplay_SkeletonRattle01);
            list.Add(AudioSourceType.SfxGameplay_SkeletonRattle02);
            list.Add(AudioSourceType.SfxGameplay_SkeletonRattle03);
            list.Add(AudioSourceType.SfxGameplay_SkeletonRattle04);
            list.Add(AudioSourceType.SfxGameplay_SkeletonRattle05);
            dictionary.Add(AudioGroupType.SfxGrpGameplay_SkeletonRattle, list);
            list = new List<AudioSourceType>();
            list.Add(AudioSourceType.SfxGameplay_SkeletonDeath01);
            list.Add(AudioSourceType.SfxGameplay_SkeletonDeath02);
            list.Add(AudioSourceType.SfxGameplay_SkeletonDeath03);
            dictionary.Add(AudioGroupType.SfxGrpGameplay_SkeletonDeath, list);
            list = new List<AudioSourceType>();
            list.Add(AudioSourceType.SfxGameplay_PygmyNoise01);
            list.Add(AudioSourceType.SfxGameplay_PygmyNoise02);
            list.Add(AudioSourceType.SfxGameplay_PygmyNoise03);
            list.Add(AudioSourceType.SfxGameplay_PygmyRattle01);
            list.Add(AudioSourceType.SfxGameplay_PygmyRattle02);
            list.Add(AudioSourceType.SfxGameplay_PygmyRattle03);
            list.Add(AudioSourceType.SfxGameplay_PygmyRattle04);
            dictionary.Add(AudioGroupType.SfxGrpGameplay_PygmyNoise, list);
            list = new List<AudioSourceType>();
            list.Add(AudioSourceType.SfxGameplay_PygmyDeath01);
            list.Add(AudioSourceType.SfxGameplay_PygmyDeath02);
            list.Add(AudioSourceType.SfxGameplay_PygmyDeath03);
            dictionary.Add(AudioGroupType.SfxGrpGameplay_PygmyDeath, list);
            list = new List<AudioSourceType>();
            list.Add(AudioSourceType.SfxGameplay_PygmyRattle01);
            list.Add(AudioSourceType.SfxGameplay_PygmyRattle02);
            list.Add(AudioSourceType.SfxGameplay_PygmyRattle03);
            list.Add(AudioSourceType.SfxGameplay_PygmyRattle04);
            dictionary.Add(AudioGroupType.SfxGrpGameplay_PygmyRattle, list);
            list = new List<AudioSourceType>();
            list.Add(AudioSourceType.SfxGameplay_CrocNoise01);
            list.Add(AudioSourceType.SfxGameplay_CrocNoise02);
            list.Add(AudioSourceType.SfxGameplay_CrocNoise03);
            dictionary.Add(AudioGroupType.SfxGrpGameplay_CrocNoise, list);
            list = new List<AudioSourceType>();
            list.Add(AudioSourceType.SfxGameplay_CrocDeath01);
            list.Add(AudioSourceType.SfxGameplay_CrocDeath02);
            dictionary.Add(AudioGroupType.SfxGrpGameplay_CrocDeath, list);
            list = new List<AudioSourceType>();
            list.Add(AudioSourceType.SfxGameplay_AnubisNoise01);
            list.Add(AudioSourceType.SfxGameplay_AnubisNoise02);
            list.Add(AudioSourceType.SfxGameplay_AnubisNoise03);
            list.Add(AudioSourceType.SfxGameplay_AnubisNoise04);
            dictionary.Add(AudioGroupType.SfxGrpGameplay_AnubisNoise, list);
            list = new List<AudioSourceType>();
            list.Add(AudioSourceType.SfxGameplay_AnubisDeath01);
            list.Add(AudioSourceType.SfxGameplay_AnubisDeath02);
            list.Add(AudioSourceType.SfxGameplay_AnubisDeath03);
            dictionary.Add(AudioGroupType.SfxGrpGameplay_AnubisDeath, list);
            list = new List<AudioSourceType>();
            list.Add(AudioSourceType.SfxGameplay_GoblinNoise01);
            list.Add(AudioSourceType.SfxGameplay_GoblinNoise02);
            list.Add(AudioSourceType.SfxGameplay_GoblinNoise03);
            list.Add(AudioSourceType.SfxGameplay_GoblinNoise04);
            dictionary.Add(AudioGroupType.SfxGrpGameplay_GoblinNoise, list);
            list = new List<AudioSourceType>();
            list.Add(AudioSourceType.SfxGameplay_GoblinDeath01);
            list.Add(AudioSourceType.SfxGameplay_GoblinDeath02);
            list.Add(AudioSourceType.SfxGameplay_GoblinDeath03);
            dictionary.Add(AudioGroupType.SfxGrpGameplay_GoblinDeath, list);
            list = new List<AudioSourceType>();
            list.Add(AudioSourceType.SfxGameplay_MummyNoise01);
            list.Add(AudioSourceType.SfxGameplay_MummyNoise02);
            list.Add(AudioSourceType.SfxGameplay_MummyNoise03);
            dictionary.Add(AudioGroupType.SfxGrpGameplay_MummyNoise, list);
            list = new List<AudioSourceType>();
            list.Add(AudioSourceType.SfxGameplay_MummyDeath01);
            list.Add(AudioSourceType.SfxGameplay_MummyDeath02);
            list.Add(AudioSourceType.SfxGameplay_MummyDeath03);
            dictionary.Add(AudioGroupType.SfxGrpGameplay_MummyDeath, list);
            list = new List<AudioSourceType>();
            list.Add(AudioSourceType.SfxGameplay_RatNoise01);
            list.Add(AudioSourceType.SfxGameplay_RatNoise02);
            list.Add(AudioSourceType.SfxGameplay_RatNoise03);
            list.Add(AudioSourceType.SfxGameplay_RatNoise04);
            dictionary.Add(AudioGroupType.SfxGrpGameplay_RatNoise, list);
            list = new List<AudioSourceType>();
            list.Add(AudioSourceType.SfxGameplay_RatDeath01);
            list.Add(AudioSourceType.SfxGameplay_RatDeath02);
            list.Add(AudioSourceType.SfxGameplay_RatDeath03);
            list.Add(AudioSourceType.SfxGameplay_RatDeath04);
            dictionary.Add(AudioGroupType.SfxGrpGameplay_RatDeath, list);
            list = new List<AudioSourceType>();
            list.Add(AudioSourceType.SfxGameplay_YetiNoise01);
            list.Add(AudioSourceType.SfxGameplay_YetiNoise02);
            list.Add(AudioSourceType.SfxGameplay_YetiNoise03);
            list.Add(AudioSourceType.SfxGameplay_YetiNoise04);
            dictionary.Add(AudioGroupType.SfxGrpGameplay_YetiNoise, list);
            list = new List<AudioSourceType>();
            list.Add(AudioSourceType.SfxGameplay_YetiDeath01);
            list.Add(AudioSourceType.SfxGameplay_YetiDeath02);
            list.Add(AudioSourceType.SfxGameplay_YetiDeath03);
            list.Add(AudioSourceType.SfxGameplay_YetiDeath04);
            dictionary.Add(AudioGroupType.SfxGrpGameplay_YetiDeath, list);
            list = new List<AudioSourceType>();
            list.Add(AudioSourceType.SfxGameplay_ShroomNoise01);
            list.Add(AudioSourceType.SfxGameplay_ShroomNoise02);
            list.Add(AudioSourceType.SfxGameplay_ShroomNoise03);
            dictionary.Add(AudioGroupType.SfxGrpGameplay_ShroomNoise, list);
            list = new List<AudioSourceType>();
            list.Add(AudioSourceType.SfxGameplay_ShroomDeath01);
            list.Add(AudioSourceType.SfxGameplay_ShroomDeath02);
            list.Add(AudioSourceType.SfxGameplay_ShroomDeath03);
            dictionary.Add(AudioGroupType.SfxGrpGameplay_ShroomDeath, list);
            list = new List<AudioSourceType>();
            list.Add(AudioSourceType.SfxGameplay_ShroomPuff01);
            list.Add(AudioSourceType.SfxGameplay_ShroomPuff02);
            list.Add(AudioSourceType.SfxGameplay_ShroomPuff03);
            list.Add(AudioSourceType.SfxGameplay_ShroomPuff04);
            dictionary.Add(AudioGroupType.SfxGrpGameplay_ShroomPuff, list);
            list = new List<AudioSourceType>();
            list.Add(AudioSourceType.SfxGameplay_JellyMove01);
            list.Add(AudioSourceType.SfxGameplay_JellyMove02);
            list.Add(AudioSourceType.SfxGameplay_JellyMove03);
            list.Add(AudioSourceType.SfxGameplay_JellyMove04);
            list.Add(AudioSourceType.SfxGameplay_JellyMove05);
            list.Add(AudioSourceType.SfxGameplay_JellyMove06);
            dictionary.Add(AudioGroupType.SfxGrpGameplay_JellyMove, list);
            list = new List<AudioSourceType>();
            list.Add(AudioSourceType.SfxGameplay_JellyDeath01);
            list.Add(AudioSourceType.SfxGameplay_JellyDeath02);
            dictionary.Add(AudioGroupType.SfxGrpGameplay_JellyDeath, list);
            list = new List<AudioSourceType>();
            list.Add(AudioSourceType.SfxGameplay_WoodenShieldLayer01);
            list.Add(AudioSourceType.SfxGameplay_WoodenShieldLayer02);
            list.Add(AudioSourceType.SfxGameplay_WoodenShieldLayer03);
            list.Add(AudioSourceType.SfxGameplay_WoodenShieldLayer04);
            dictionary.Add(AudioGroupType.SfxGrpGameplay_WoodenShieldLayer, list);
            list = new List<AudioSourceType>();
            list.Add(AudioSourceType.SfxGameplay_ResourceCoin01);
            list.Add(AudioSourceType.SfxGameplay_ResourceCoin02);
            list.Add(AudioSourceType.SfxGameplay_ResourceCoin03);
            list.Add(AudioSourceType.SfxGameplay_ResourceCoin04);
            list.Add(AudioSourceType.SfxGameplay_ResourceCoin05);
            list.Add(AudioSourceType.SfxGameplay_ResourceCoin06);
            list.Add(AudioSourceType.SfxGameplay_ResourceCoin07);
            dictionary.Add(AudioGroupType.SfxGrpGameplay_ResourceCoin, list);
            list = new List<AudioSourceType>();
            list.Add(AudioSourceType.SfxGameplay_ResourceDiamond01);
            list.Add(AudioSourceType.SfxGameplay_ResourceDiamond02);
            list.Add(AudioSourceType.SfxGameplay_ResourceDiamond03);
            list.Add(AudioSourceType.SfxGameplay_ResourceDiamond04);
            dictionary.Add(AudioGroupType.SfxGrpGameplay_ResourceDiamond, list);
            list = new List<AudioSourceType>();
            list.Add(AudioSourceType.SfxGameplay_FrenzyTeleport01);
            list.Add(AudioSourceType.SfxGameplay_FrenzyTeleport02);
            list.Add(AudioSourceType.SfxGameplay_FrenzyTeleport03);
            dictionary.Add(AudioGroupType.SfxGrpGameplay_FrenzyTeleport, list);
            list = new List<AudioSourceType>();
            list.Add(AudioSourceType.SfxGameplay_PetWalrusVoice01);
            list.Add(AudioSourceType.SfxGameplay_PetWalrusVoice02);
            list.Add(AudioSourceType.SfxGameplay_PetWalrusVoice03);
            list.Add(AudioSourceType.SfxGameplay_PetWalrusVoice04);
            list.Add(AudioSourceType.SfxGameplay_PetWalrusVoice05);
            dictionary.Add(AudioGroupType.SfxGrpGameplay_PetWalrusVoice, list);
            list = new List<AudioSourceType>();
            list.Add(AudioSourceType.SfxGameplay_PetMooseVoice01);
            list.Add(AudioSourceType.SfxGameplay_PetMooseVoice02);
            list.Add(AudioSourceType.SfxGameplay_PetMooseVoice03);
            list.Add(AudioSourceType.SfxGameplay_PetMooseVoice04);
            list.Add(AudioSourceType.SfxGameplay_PetMooseVoice05);
            dictionary.Add(AudioGroupType.SfxGrpGameplay_PetMooseVoice, list);
            list = new List<AudioSourceType>();
            list.Add(AudioSourceType.SfxGameplay_PetDogBark01);
            list.Add(AudioSourceType.SfxGameplay_PetDogBark02);
            list.Add(AudioSourceType.SfxGameplay_PetDogBark03);
            list.Add(AudioSourceType.SfxGameplay_PetDogBark04);
            list.Add(AudioSourceType.SfxGameplay_PetDogBark05);
            dictionary.Add(AudioGroupType.SfxGrpGameplay_PetDogBark, list);
            list = new List<AudioSourceType>();
            list.Add(AudioSourceType.SfxGameplay_PetSharkBite01);
            list.Add(AudioSourceType.SfxGameplay_PetSharkBite02);
            list.Add(AudioSourceType.SfxGameplay_PetSharkBite03);
            dictionary.Add(AudioGroupType.SfxGrpGameplay_PetSharkBite, list);
            list = new List<AudioSourceType>();
            list.Add(AudioSourceType.SfxGameplay_PetGorillaVoice01);
            list.Add(AudioSourceType.SfxGameplay_PetGorillaVoice02);
            list.Add(AudioSourceType.SfxGameplay_PetGorillaVoice03);
            list.Add(AudioSourceType.SfxGameplay_PetGorillaVoice04);
            list.Add(AudioSourceType.SfxGameplay_PetGorillaVoice05);
            dictionary.Add(AudioGroupType.SfxGrpGameplay_PetGorillaVoice, list);
            list = new List<AudioSourceType>();
            list.Add(AudioSourceType.SfxGameplay_PetCrabVoice01);
            list.Add(AudioSourceType.SfxGameplay_PetCrabVoice02);
            list.Add(AudioSourceType.SfxGameplay_PetCrabVoice03);
            list.Add(AudioSourceType.SfxGameplay_PetCrabVoice04);
            list.Add(AudioSourceType.SfxGameplay_PetCrabVoice05);
            dictionary.Add(AudioGroupType.SfxGrpGameplay_PetCrabVoice, list);
            list = new List<AudioSourceType>();
            list.Add(AudioSourceType.SfxGameplay_PetTreeRustle01);
            list.Add(AudioSourceType.SfxGameplay_PetTreeRustle02);
            list.Add(AudioSourceType.SfxGameplay_PetTreeRustle03);
            dictionary.Add(AudioGroupType.SfxGrpGameplay_PetTreeRustle, list);
            list = new List<AudioSourceType>();
            list.Add(AudioSourceType.SfxGameplay_PetRamVoice01);
            list.Add(AudioSourceType.SfxGameplay_PetRamVoice02);
            list.Add(AudioSourceType.SfxGameplay_PetRamVoice03);
            dictionary.Add(AudioGroupType.SfxGrpGameplay_PetRamVoice, list);
            list = new List<AudioSourceType>();
            list.Add(AudioSourceType.SfxGameplay_PetChesterVoice01);
            list.Add(AudioSourceType.SfxGameplay_PetChesterVoice02);
            list.Add(AudioSourceType.SfxGameplay_PetChesterVoice03);
            list.Add(AudioSourceType.SfxGameplay_PetChesterVoice04);
            dictionary.Add(AudioGroupType.SfxGrpGameplay_PetChesterVoice, list);
            list = new List<AudioSourceType>();
            list.Add(AudioSourceType.SfxGameplay_PetJadeVoice01);
            list.Add(AudioSourceType.SfxGameplay_PetJadeVoice02);
            list.Add(AudioSourceType.SfxGameplay_PetJadeVoice03);
            list.Add(AudioSourceType.SfxGameplay_PetJadeVoice04);
            list.Add(AudioSourceType.SfxGameplay_PetJadeVoice05);
            dictionary.Add(AudioGroupType.SfxGrpGameplay_PetJadeVoice, list);
            list = new List<AudioSourceType>();
            list.Add(AudioSourceType.SfxGameplay_PetAttackPunch01);
            list.Add(AudioSourceType.SfxGameplay_PetAttackPunch02);
            list.Add(AudioSourceType.SfxGameplay_PetAttackPunch03);
            list.Add(AudioSourceType.SfxGameplay_PetAttackPunch04);
            dictionary.Add(AudioGroupType.SfxGrpGameplay_PetAttackPunch, list);
            list = new List<AudioSourceType>();
            list.Add(AudioSourceType.SfxGameplay_PetAttackCoin01);
            list.Add(AudioSourceType.SfxGameplay_PetAttackCoin02);
            list.Add(AudioSourceType.SfxGameplay_PetAttackCoin03);
            list.Add(AudioSourceType.SfxGameplay_PetAttackCoin04);
            dictionary.Add(AudioGroupType.SfxGrpGameplay_PetAttackCoin, list);
            list = new List<AudioSourceType>();
            list.Add(AudioSourceType.SfxGameplay_PetAttackGunshot01);
            list.Add(AudioSourceType.SfxGameplay_PetAttackGunshot02);
            list.Add(AudioSourceType.SfxGameplay_PetAttackGunshot03);
            list.Add(AudioSourceType.SfxGameplay_PetAttackGunshot04);
            dictionary.Add(AudioGroupType.SfxGrpGameplay_PetAttackGunshot, list);
            list = new List<AudioSourceType>();
            list.Add(AudioSourceType.SfxGameplay_PetAttackThrow01);
            list.Add(AudioSourceType.SfxGameplay_PetAttackThrow02);
            list.Add(AudioSourceType.SfxGameplay_PetAttackThrow03);
            dictionary.Add(AudioGroupType.SfxGrpGameplay_PetAttackThrow, list);
            list = new List<AudioSourceType>();
            list.Add(AudioSourceType.SfxGameplay_PetAttackSquirt01);
            list.Add(AudioSourceType.SfxGameplay_PetAttackSquirt02);
            list.Add(AudioSourceType.SfxGameplay_PetAttackSquirt03);
            list.Add(AudioSourceType.SfxGameplay_PetAttackSquirt04);
            dictionary.Add(AudioGroupType.SfxGrpGameplay_PetAttackSquirt, list);
            list = new List<AudioSourceType>();
            list.Add(AudioSourceType.SfxGameplay_PetAttackHeadbutt01);
            list.Add(AudioSourceType.SfxGameplay_PetAttackHeadbutt02);
            list.Add(AudioSourceType.SfxGameplay_PetAttackHeadbutt03);
            dictionary.Add(AudioGroupType.SfxGrpGameplay_PetAttackHeadbutt, list);
            list = new List<AudioSourceType>();
            list.Add(AudioSourceType.SfxGameplay_PetAttackHitFoliage01);
            list.Add(AudioSourceType.SfxGameplay_PetAttackHitFoliage02);
            list.Add(AudioSourceType.SfxGameplay_PetAttackHitFoliage03);
            list.Add(AudioSourceType.SfxGameplay_PetAttackHitFoliage04);
            dictionary.Add(AudioGroupType.SfxGrpGameplay_PetAttackHitFoliage, list);
            list = new List<AudioSourceType>();
            list.Add(AudioSourceType.SfxGameplay_PetAttackHitBoulder01);
            list.Add(AudioSourceType.SfxGameplay_PetAttackHitBoulder02);
            list.Add(AudioSourceType.SfxGameplay_PetAttackHitBoulder03);
            list.Add(AudioSourceType.SfxGameplay_PetAttackHitBoulder04);
            list.Add(AudioSourceType.SfxGameplay_PetAttackHitBoulder05);
            dictionary.Add(AudioGroupType.SfxGrpGameplay_PetAttackHitBoulder, list);
            list = new List<AudioSourceType>();
            list.Add(AudioSourceType.SfxGameplay_PetSkillDash01);
            list.Add(AudioSourceType.SfxGameplay_PetSkillDash02);
            list.Add(AudioSourceType.SfxGameplay_PetSkillDash03);
            dictionary.Add(AudioGroupType.SfxGrpGameplay_PetSkillDash, list);
            list = new List<AudioSourceType>();
            list.Add(AudioSourceType.SfxGameplay_PetSkillWhirl01);
            list.Add(AudioSourceType.SfxGameplay_PetSkillWhirl02);
            list.Add(AudioSourceType.SfxGameplay_PetSkillWhirl03);
            dictionary.Add(AudioGroupType.SfxGrpGameplay_PetSkillWhirl, list);
            list = new List<AudioSourceType>();
            list.Add(AudioSourceType.SfxGameplay_SmashPot01);
            list.Add(AudioSourceType.SfxGameplay_SmashPot02);
            list.Add(AudioSourceType.SfxGameplay_SmashPot03);
            list.Add(AudioSourceType.SfxGameplay_SmashPot04);
            dictionary.Add(AudioGroupType.SfxGrpGameplay_SmashPot, list);
            list = new List<AudioSourceType>();
            list.Add(AudioSourceType.SfxGameplay_SmashCrate01);
            list.Add(AudioSourceType.SfxGameplay_SmashCrate02);
            list.Add(AudioSourceType.SfxGameplay_SmashCrate03);
            list.Add(AudioSourceType.SfxGameplay_SmashCrate04);
            dictionary.Add(AudioGroupType.SfxGrpGameplay_SmashCrate, list);
            list = new List<AudioSourceType>();
            list.Add(AudioSourceType.SfxGameplay_SmashPumpkin01);
            list.Add(AudioSourceType.SfxGameplay_SmashPumpkin02);
            list.Add(AudioSourceType.SfxGameplay_SmashPumpkin03);
            list.Add(AudioSourceType.SfxGameplay_SmashPumpkin04);
            dictionary.Add(AudioGroupType.SfxGrpGameplay_SmashPumpkin, list);
            list = new List<AudioSourceType>();
            list.Add(AudioSourceType.SfxGameplay_SmashPoison01);
            list.Add(AudioSourceType.SfxGameplay_SmashPoison02);
            list.Add(AudioSourceType.SfxGameplay_SmashPoison03);
            list.Add(AudioSourceType.SfxGameplay_SmashPoison04);
            dictionary.Add(AudioGroupType.SfxGrpGameplay_SmashPoison, list);
            list = new List<AudioSourceType>();
            list.Add(AudioSourceType.SfxUi_ItemRankUp01);
            list.Add(AudioSourceType.SfxUi_ItemRankUp02);
            dictionary.Add(AudioGroupType.SfxGrpUi_ItemRankUp, list);
            list = new List<AudioSourceType>();
            list.Add(AudioSourceType.SfxUi_Reroll01);
            list.Add(AudioSourceType.SfxUi_Reroll02);
            list.Add(AudioSourceType.SfxUi_Reroll03);
            dictionary.Add(AudioGroupType.SfxGrpUi_Reroll, list);
            list = new List<AudioSourceType>();
            list.Add(AudioSourceType.SfxUi_ResourceCoin01);
            list.Add(AudioSourceType.SfxUi_ResourceCoin02);
            list.Add(AudioSourceType.SfxUi_ResourceCoin03);
            list.Add(AudioSourceType.SfxUi_ResourceCoin04);
            list.Add(AudioSourceType.SfxUi_ResourceCoin05);
            list.Add(AudioSourceType.SfxUi_ResourceCoin06);
            list.Add(AudioSourceType.SfxUi_ResourceCoin07);
            dictionary.Add(AudioGroupType.SfxGrpUi_ResourceCoin, list);
            list = new List<AudioSourceType>();
            list.Add(AudioSourceType.SfxUi_ResourceDiamond01);
            list.Add(AudioSourceType.SfxUi_ResourceDiamond02);
            list.Add(AudioSourceType.SfxUi_ResourceDiamond03);
            list.Add(AudioSourceType.SfxUi_ResourceDiamond04);
            dictionary.Add(AudioGroupType.SfxGrpUi_ResourceDiamond, list);
            list = new List<AudioSourceType>();
            list.Add(AudioSourceType.SfxUi_BagOpen01);
            list.Add(AudioSourceType.SfxUi_BagOpen02);
            list.Add(AudioSourceType.SfxUi_BagOpen03);
            list.Add(AudioSourceType.SfxUi_BagOpen04);
            list.Add(AudioSourceType.SfxUi_BagOpen05);
            dictionary.Add(AudioGroupType.SfxGrpUi_BagOpen, list);
            list = new List<AudioSourceType>();
            list.Add(AudioSourceType.SfxUi_BagClose01);
            list.Add(AudioSourceType.SfxUi_BagClose02);
            list.Add(AudioSourceType.SfxUi_BagClose03);
            list.Add(AudioSourceType.SfxUi_BagClose04);
            list.Add(AudioSourceType.SfxUi_BagClose05);
            dictionary.Add(AudioGroupType.SfxGrpUi_BagClose, list);
            list = new List<AudioSourceType>();
            list.Add(AudioSourceType.SfxUi_BookOpen01);
            list.Add(AudioSourceType.SfxUi_BookOpen02);
            list.Add(AudioSourceType.SfxUi_BookOpen03);
            dictionary.Add(AudioGroupType.SfxGrpUi_BookOpen, list);
            list = new List<AudioSourceType>();
            list.Add(AudioSourceType.SfxUi_BookClose01);
            list.Add(AudioSourceType.SfxUi_BookClose02);
            list.Add(AudioSourceType.SfxUi_BookClose03);
            dictionary.Add(AudioGroupType.SfxGrpUi_BookClose, list);
            list = new List<AudioSourceType>();
            list.Add(AudioSourceType.SfxUi_BookTurn01);
            list.Add(AudioSourceType.SfxUi_BookTurn02);
            list.Add(AudioSourceType.SfxUi_BookTurn03);
            list.Add(AudioSourceType.SfxUi_BookTurn04);
            list.Add(AudioSourceType.SfxUi_BookTurn05);
            dictionary.Add(AudioGroupType.SfxGrpUi_BookTurn, list);
            list = new List<AudioSourceType>();
            list.Add(AudioSourceType.SfxUi_ClockTick01);
            list.Add(AudioSourceType.SfxUi_ClockTick02);
            list.Add(AudioSourceType.SfxUi_ClockTick03);
            list.Add(AudioSourceType.SfxUi_ClockTick04);
            dictionary.Add(AudioGroupType.SfxGrpUi_ClockTick, list);
            SFX_AUDIO_GROUPS = dictionary;
        }
    }
}

